// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	RunID      string             `json:"run_id"`
	DecisionID string             `json:"decision_id"`
	RequiredAt pgtype.Timestamptz `json:"required_at"`
	Reason     pgtype.Text        `json:"reason"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	Decision   pgtype.Text        `json:"decision"`
	Resolver   []byte             `json:"resolver"`
}

type AuditEvent struct {
	ID        string             `json:"id"`
	RunID     string             `json:"run_id"`
	Kind      string             `json:"kind"`
	Detail    []byte             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IntentType struct {
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Schema       []byte             `json:"schema"`
	Policy       []byte             `json:"policy"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type ProvenanceStep struct {
	ID          string             `json:"id"`
	RunID       string             `json:"run_id"`
	Iteration   int32              `json:"iteration"`
	Stage       string             `json:"stage"`
	Layer       string             `json:"layer"`
	LayerRef    pgtype.Text        `json:"layer_ref"`
	Inputs      []byte             `json:"inputs"`
	Outputs     []byte             `json:"outputs"`
	Error       []byte             `json:"error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Run struct {
	ID              string             `json:"id"`
	TenantOrg       string             `json:"tenant_org"`
	TenantTeam      string             `json:"tenant_team"`
	TenantUser      string             `json:"tenant_user"`
	IntentType      string             `json:"intent_type"`
	IntentPayload   []byte             `json:"intent_payload"`
	IntentSubject   pgtype.Text        `json:"intent_subject"`
	SessionID       string             `json:"session_id"`
	CallerType      string             `json:"caller_type"`
	CallerID        string             `json:"caller_id"`
	CallerName      pgtype.Text        `json:"caller_name"`
	Scope           []string           `json:"scope"`
	Status          string             `json:"status"`
	Iteration       int32              `json:"iteration"`
	Goal            []byte             `json:"goal"`
	LastError       []byte             `json:"last_error"`
	PendingDecision []byte             `json:"pending_decision"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type Session struct {
	ID         string             `json:"id"`
	TenantOrg  string             `json:"tenant_org"`
	TenantTeam string             `json:"tenant_team"`
	TenantUser string             `json:"tenant_user"`
	CallerType string             `json:"caller_type"`
	CallerID   string             `json:"caller_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
