// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
insert into audit_events (id, run_id, kind, detail, created_at)
values ($1, $2, $3, $4, $5)
on conflict(id) do nothing
`

type AppendAuditEventParams struct {
	ID        string             `json:"id"`
	RunID     string             `json:"run_id"`
	Kind      string             `json:"kind"`
	Detail    []byte             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.Exec(ctx, appendAuditEvent,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const getRun = `-- name: GetRun :one

select id, intent_type, intent_payload, intent_subject, session_id,
       caller_type, caller_id, caller_name, scope, status, iteration,
       goal, last_error, started_at, updated_at, completed_at
from runs where id = $1
`

type GetRunRow struct {
	ID            string             `json:"id"`
	IntentType    string             `json:"intent_type"`
	IntentPayload []byte             `json:"intent_payload"`
	IntentSubject pgtype.Text        `json:"intent_subject"`
	SessionID     string             `json:"session_id"`
	CallerType    string             `json:"caller_type"`
	CallerID      string             `json:"caller_id"`
	CallerName    pgtype.Text        `json:"caller_name"`
	Scope         []string           `json:"scope"`
	Status        string             `json:"status"`
	Iteration     int32              `json:"iteration"`
	Goal          []byte             `json:"goal"`
	LastError     []byte             `json:"last_error"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

// Olymp Postgres queries (sqlc generation target). Hand-written backend in
// internal/store/postgres is the canonical implementation today; this file
// exists so `sqlc generate` produces a typed mirror when we migrate.
func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.IntentType,
		&i.IntentPayload,
		&i.IntentSubject,
		&i.SessionID,
		&i.CallerType,
		&i.CallerID,
		&i.CallerName,
		&i.Scope,
		&i.Status,
		&i.Iteration,
		&i.Goal,
		&i.LastError,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAuditForRun = `-- name: ListAuditForRun :many
select id, run_id, kind, detail, created_at
from audit_events
where run_id = $1
order by created_at
`

func (q *Queries) ListAuditForRun(ctx context.Context, runID string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
select id, intent_type, intent_payload, intent_subject, session_id,
       caller_type, caller_id, caller_name, scope, status, iteration,
       goal, last_error, started_at, updated_at, completed_at
from runs
order by started_at desc
limit $1
`

type ListRunsRow struct {
	ID            string             `json:"id"`
	IntentType    string             `json:"intent_type"`
	IntentPayload []byte             `json:"intent_payload"`
	IntentSubject pgtype.Text        `json:"intent_subject"`
	SessionID     string             `json:"session_id"`
	CallerType    string             `json:"caller_type"`
	CallerID      string             `json:"caller_id"`
	CallerName    pgtype.Text        `json:"caller_name"`
	Scope         []string           `json:"scope"`
	Status        string             `json:"status"`
	Iteration     int32              `json:"iteration"`
	Goal          []byte             `json:"goal"`
	LastError     []byte             `json:"last_error"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListRuns(ctx context.Context, limit int32) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntentType,
			&i.IntentPayload,
			&i.IntentSubject,
			&i.SessionID,
			&i.CallerType,
			&i.CallerID,
			&i.CallerName,
			&i.Scope,
			&i.Status,
			&i.Iteration,
			&i.Goal,
			&i.LastError,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
update runs set status = $1, updated_at = $2 where id = $3
`

type UpdateRunStatusParams struct {
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
