// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Approval struct {
	RunID      string         `json:"run_id"`
	DecisionID string         `json:"decision_id"`
	RequiredAt string         `json:"required_at"`
	Reason     sql.NullString `json:"reason"`
	ResolvedAt sql.NullString `json:"resolved_at"`
	Decision   sql.NullString `json:"decision"`
	Resolver   sql.NullString `json:"resolver"`
}

type AuditEvent struct {
	ID        string `json:"id"`
	RunID     string `json:"run_id"`
	Kind      string `json:"kind"`
	Detail    string `json:"detail"`
	CreatedAt string `json:"created_at"`
}

type IntentType struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Schema       string         `json:"schema"`
	Policy       string         `json:"policy"`
	RegisteredAt string         `json:"registered_at"`
}

type ProvenanceStep struct {
	ID          string         `json:"id"`
	RunID       string         `json:"run_id"`
	Iteration   int64          `json:"iteration"`
	Stage       string         `json:"stage"`
	Layer       string         `json:"layer"`
	LayerRef    sql.NullString `json:"layer_ref"`
	Inputs      string         `json:"inputs"`
	Outputs     string         `json:"outputs"`
	Error       sql.NullString `json:"error"`
	StartedAt   string         `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

type Run struct {
	ID              string         `json:"id"`
	TenantOrg       string         `json:"tenant_org"`
	TenantTeam      string         `json:"tenant_team"`
	TenantUser      string         `json:"tenant_user"`
	IntentType      string         `json:"intent_type"`
	IntentPayload   string         `json:"intent_payload"`
	IntentSubject   sql.NullString `json:"intent_subject"`
	SessionID       string         `json:"session_id"`
	CallerType      string         `json:"caller_type"`
	CallerID        string         `json:"caller_id"`
	CallerName      sql.NullString `json:"caller_name"`
	Scope           string         `json:"scope"`
	Status          string         `json:"status"`
	Iteration       int64          `json:"iteration"`
	Goal            string         `json:"goal"`
	LastError       sql.NullString `json:"last_error"`
	PendingDecision sql.NullString `json:"pending_decision"`
	StartedAt       string         `json:"started_at"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
}

type Session struct {
	ID         string `json:"id"`
	TenantOrg  string `json:"tenant_org"`
	TenantTeam string `json:"tenant_team"`
	TenantUser string `json:"tenant_user"`
	CallerType string `json:"caller_type"`
	CallerID   string `json:"caller_id"`
	Metadata   string `json:"metadata"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}
