// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error
	// Olymp SQLite queries (sqlc generation target). Hand-written backend in
	// internal/store/sqlite is the canonical implementation today; this file
	// exists so `sqlc generate` produces a typed mirror once we choose to migrate.
	GetRun(ctx context.Context, id string) (GetRunRow, error)
	ListAuditForRun(ctx context.Context, runID string) ([]AuditEvent, error)
	ListRuns(ctx context.Context, limit int64) ([]ListRunsRow, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
}

var _ Querier = (*Queries)(nil)
