// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
insert into audit_events (id, run_id, kind, detail, created_at)
values (?, ?, ?, ?, ?)
on conflict(id) do nothing
`

type AppendAuditEventParams struct {
	ID        string `json:"id"`
	RunID     string `json:"run_id"`
	Kind      string `json:"kind"`
	Detail    string `json:"detail"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditEvent,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const getRun = `-- name: GetRun :one

select id, intent_type, intent_payload, intent_subject, session_id,
       caller_type, caller_id, caller_name, scope, status, iteration,
       goal, last_error, started_at, updated_at, completed_at
from runs where id = ?
`

type GetRunRow struct {
	ID            string         `json:"id"`
	IntentType    string         `json:"intent_type"`
	IntentPayload string         `json:"intent_payload"`
	IntentSubject sql.NullString `json:"intent_subject"`
	SessionID     string         `json:"session_id"`
	CallerType    string         `json:"caller_type"`
	CallerID      string         `json:"caller_id"`
	CallerName    sql.NullString `json:"caller_name"`
	Scope         string         `json:"scope"`
	Status        string         `json:"status"`
	Iteration     int64          `json:"iteration"`
	Goal          string         `json:"goal"`
	LastError     sql.NullString `json:"last_error"`
	StartedAt     string         `json:"started_at"`
	UpdatedAt     string         `json:"updated_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
}

// Olymp SQLite queries (sqlc generation target). Hand-written backend in
// internal/store/sqlite is the canonical implementation today; this file
// exists so `sqlc generate` produces a typed mirror once we choose to migrate.
func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.IntentType,
		&i.IntentPayload,
		&i.IntentSubject,
		&i.SessionID,
		&i.CallerType,
		&i.CallerID,
		&i.CallerName,
		&i.Scope,
		&i.Status,
		&i.Iteration,
		&i.Goal,
		&i.LastError,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAuditForRun = `-- name: ListAuditForRun :many
select id, run_id, kind, detail, created_at
from audit_events
where run_id = ?
order by created_at
`

func (q *Queries) ListAuditForRun(ctx context.Context, runID string) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
select id, intent_type, intent_payload, intent_subject, session_id,
       caller_type, caller_id, caller_name, scope, status, iteration,
       goal, last_error, started_at, updated_at, completed_at
from runs
order by started_at desc
limit ?
`

type ListRunsRow struct {
	ID            string         `json:"id"`
	IntentType    string         `json:"intent_type"`
	IntentPayload string         `json:"intent_payload"`
	IntentSubject sql.NullString `json:"intent_subject"`
	SessionID     string         `json:"session_id"`
	CallerType    string         `json:"caller_type"`
	CallerID      string         `json:"caller_id"`
	CallerName    sql.NullString `json:"caller_name"`
	Scope         string         `json:"scope"`
	Status        string         `json:"status"`
	Iteration     int64          `json:"iteration"`
	Goal          string         `json:"goal"`
	LastError     sql.NullString `json:"last_error"`
	StartedAt     string         `json:"started_at"`
	UpdatedAt     string         `json:"updated_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
}

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntentType,
			&i.IntentPayload,
			&i.IntentSubject,
			&i.SessionID,
			&i.CallerType,
			&i.CallerID,
			&i.CallerName,
			&i.Scope,
			&i.Status,
			&i.Iteration,
			&i.Goal,
			&i.LastError,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
update runs set status = ?, updated_at = ? where id = ?
`

type UpdateRunStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
